import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsOptional } from 'class-validator';
import { HydraNode } from '../entities/HydraNode.entity';
import { Account } from '../entities/Account.entity';

export class HydraDto {
    constructor(hydraNode: HydraNode, status: 'ACTIVE' | 'INACTIVE' = 'INACTIVE') {
        this.id = hydraNode.id;
        this.description = hydraNode.description;
        this.port = hydraNode.port;
        this.vkey = hydraNode.vkey;
        this.createdAt = hydraNode.createdAt;
        this.cardanoWallet = hydraNode.cardanoAccount;
        this.status = status;
    }

    @ApiProperty({
        type: String,
        example: '1',
    })
    @IsNotEmpty()
    id: string | number;

    @ApiProperty({
        type: String,
        example: 'Generated by party 1',
    })
    @IsOptional()
    description?: string;

    @ApiProperty({
        type: Number,
        example: 3880,
    })
    @IsNotEmpty()
    port: number;

    @ApiProperty({
        type: String,
        example:
            '{"type":"HydraVerificationKey_ed25519","description":"","cborHex":"5820c6d51b801c23f69772572f8989e2b97178d770201fcbf02b1190ac615b1c04e2"}',
    })
    @IsNotEmpty()
    vkey: string;

    @ApiProperty({
        type: String,
        example: '2024-12-22T16:23:07.879Z',
    })
    @IsNotEmpty()
    createdAt: string;

    @ApiProperty()
    @IsNotEmpty()
    cardanoWallet: Account;

    @ApiProperty({
        type: String,
        example: 'ACTIVE',
    })
    status: 'ACTIVE' | 'INACTIVE';
}
